### ISSUE TITLE
可以添加README.md

### ISSUE THREAD

**Issue by wulunshijian** [staffsang/-live-#1]
如题，里面可以添加B站视频的导向，比如指向某部live，（虽然，我觉得来到这里的应该都知道，或者说已经缓存了）

**Comment by staffsang** [comment]
加是加了，又传不上文件了，还在看咋回事（

**Comment by wulunshijian** [comment]
git add README.md
git commit -m "add readme.md"
git push -u origin master
如果担心传入文件夹其他东西，可以用.gitignore 来剔除，添加文件需要保证文件在隐藏文件夹的.git 同级目录下

**Comment by staffsang** [comment]
不是，README我是直接在这写的，但是好像因此电脑上的远程库就直接传不上东西了，不知道是不是教程说的不同步的原因，然后镜像还是拷贝来着把这个本地库同步到电脑上鼓捣了半天，姑且是弄懂上传的步骤了
